name: build-action

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle build
        env:
          KYNETICS_KEYSTORE_PASS: ${{ secrets.KYNETICS_KEYSTORE_PASS }}
          KYNETICS_KEY_PASS: ${{ secrets.KYNETICS_KEY_PASS }}
          KYNETICS_KEY_ALIAS: ${{ secrets.KYNETICS_KEY_ALIAS }}

        run: ./gradlew build
      - name: Create release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "uf-service-*/build/outputs/apk/*_key/*.apk"
          tags: true
          draft: false
